config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # GET "url", to: "controller#action"
  get '/ask', to: 'questions#ask'
  get '/answer', to: 'questions#answer'
end
# 'about', to: 'pages#about'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
    @question = params[:question]
  end

  def answer
    @question = params[:question]
    if @question == 'I am going to work'
      @answer = 'Great!'
    elsif @question[-1] == '?'
     @answer = 'Silly question, get dressed and go to work!'
    else
      @answer = "I don't care, get dressed and go to work!"
    end

    @answer
    # If the message is I am going to work, the coach will answer Great!
    # If the message has a question mark ? at the end, the coach will answer Silly question, get dressed and go to work!.
    # Otherwise the coach will answer I don't care, get dressed and go to work!

    # compute an instance variable @answer for the view to display
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Georama:wght@300&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
    <%# <%= link_to "Ask a question", ask_path %>
    <%# <%= link_to "Answer a question", answer_path %>
  </body>
</html>

app/views/questions/answer.html.erb
<h3>Question:</h3>
<h2><%= "--> #{params[:question]}" %></h2>
<h4 class="tab">-- You</h2>
<h3>Answer:</h3>
<h2><%= "--> #{@answer}" %></h2>
<h4 class="tab">-- Your coach</h2>

<%# Add a link to /ask on the answer.html.erb view using the link_to Rails helper.
 %>
<%= link_to '--> Ask a new question <--', ask_path%>
<%# The answer.html.erb will display the question you ask your
coach as well as his answer. The controller will need to read the question
from params and compute an instance variable @answer for the view to display. %>

app/views/questions/ask.html.erb
<h1>Stupid Coaching</h1>
<p>Ask your coach anything:</p>
<form action="/answer">
  <input type="text" name="question">
  <input type="submit" value="Ask!">
</form>